#!/usr/bin/env bash

# Example `dwm_autostart` file. Place this file in your $PATH.

start(){
    pidof "$1" &> /dev/null || "$@" &
}

# hotkey daemon
start sxhkd

# compositor
start picom

# notifications
start dunst

# network manager
start nm-applet

# automatically lock screen after 10 minutes
start xautolock -time 10 -locker i3lock

# make the mouse invisible after a brief period of not using it.
start unclutter

# dashboard
start conky

# apply Xresources
start xrdb ~/.Xresources

# set cursor speed
start xset r rate 200 45

# update dwm status bar every 10 seconds
while true; do
    sleep 2s
    dwm_status &> /dev/null & # add dwm_status to $PATH
    sleep 8s
done &

# check battery status every 10 minutes
while true; do
    sleep 10s
    capacity=$(cat /sys/class/power_supply/BAT*/capacity | head -1)
    [ -z $capacity ] && break
    batstatus=$(cat /sys/class/power_supply/BAT*/status | head -1)
    if [ "$batstatus" = "Discharging" ] && [ "$capacity" -lt 5 ]; then
        notify-send --urgency=CRITICAL "battery low" "   $capacity%" &
    fi
    sleep 590s
done &

